### PR TITLE
fix: Prevented opening of search widget in textarea while writing a /…

### LINKED ISSUE #1609: Headless CMS - Trying to write a / in textarea opens the search widget
## This is:
- Bug

## Expected Behavior
Typing a `/` in textareas should treat it as a regular character.

## Actual Behavior
Hitting `/` opens the Search widget in the top app bar.

## Steps to Reproduce the Problem
1. Setup a content model with a textarea field.
2. Open content entry form, and try typing `https://`
3. Hitting `/` will open the search widget.

## Possible Solution
 `/` is a shortcut for `search` operation, and we already handle the event coming from `INPUT`, but not from `TEXTAREA`:
https://github.com/webiny/webiny-js/blob/next/packages/app-admin/src/plugins/globalSearch/index.tsx#L13

Improving the `if` statement in the plugin linked above should do the trick. 
```ts
// Define a list of all node types we want to prevent the event from.
const ignoreNodes= ["INPUT", "TEXTAREA"];

if (ignoreNodes.includes(e.target.nodeName)) {
    return true;
}
```

### PR DESCRIPTION
**Pull request by ankurvr**
… (slash).

## Changes

Closes #1609 

## How Has This Been Tested?
Tested in by typing in text area. It works fine.

### CODE REVIEW

**Comment by adrians5j** [comment]
Looks good, just check the prettier issue and we should be good to go.

Thank you 🍻

**Comment by ankurvr** [comment]
After merging #1624 prettier issue will get fixed. Because it was coming from #1623.

**Comment by adrians5j** [comment]
Cool, will take a look and merge. Then you can merge everything back to this PR.

Hold on :)

**Comment by ankurvr** [comment]
@doitadrian This PR is also ready to merge now.

**Review by adrians5j — APPROVED** [review]

**Comment by adrians5j** [comment]
Nice hat-trick @ankurvr 🙂 

🍻 

Just wanted to ask you, can I add you to our contributors list (on our main README) file?

**Comment by ankurvr** [comment]
> Nice hat-trick @ankurvr 
> 
> 
> 
> Just wanted to ask you, can I add you to our contributors list (on our main README) file?

I will love that.

Also let me know if i am eligible fort the Swag. I will send email too.

**Comment by adrians5j** [comment]
Definitely @ankurvr 🙂 

Can you send me your e-mail, privately via Slack, and I'll make sure somebody gets in touch with you?

Thanks!

**Pull request merged**
