### PR TITLE
fix: fix page blocks list render

### PR DESCRIPTION
**Pull request by neatbyte-vnobis**
## Changes
Fix issue "List of blocks bug (URGENT)"

## How Has This Been Tested?
Manual

## Documentation
None

### CODE REVIEW

**Comment by neatbyte-vnobis** [comment]
@SvenAlHamad 
Here is a fix for an "List of blocks bug (URGENT)" issue.
I will keep in mind that such case can happen with this component for future tasks

**Comment by adrians5j** [comment]
@SvenAlHamad we should release this in our next patch release I suppose?

If so, we'll need to change the target branch here, should be `dev` then.

**Comment by neatbyte-vnobis** [comment]
@adrians5j @SvenAlHamad 
I think in this case I need to create additional PR targeting `dev`
please confirm

**Comment by SvenAlHamad** [comment]
I've test this, and it looks good. @Pavel910 can we release this in the next patch release?

**Comment by Pavel910** [comment]
@SvenAlHamad we'll be doing merges between `dev` and `next` tomorrow, when Adrian is back, and if necessary I'll extract this fix into a new PR against `dev` (if we jsut switch the base branch now, we'll get tons of modified files). So I'm adding a milestone for this to 5.34.3, and we'll see what to do about this during the week.

**Comment by adrians5j** [comment]
We'll merge this into `next` now.

But note one thing @neatbyte-vnobis: in the future, we'll need to see what's the base branch when creating a new branch - `dev` or `next`.

For example, this fix will be released as a `5.34.3` patch version, and because of that, it needed to go into `dev`. Because this branch was created from `next`, I cannot just switch the target here from `next` to `dev`, because that would also merge a lot of changes that are already in `next`, but are not ready for `dev` yet (will be at the end of Q1).

For now, I can tell you whenever we have something that's urgent, you need to branch from `dev`. 

BTW more on our branching/release strategy can be found [here](https://www.webiny.com/docs/release-management/branching-strategy).

**Pull request merged**
