### PR TITLE
fix: fix unreadable form submission values

### PR DESCRIPTION
**Pull request by neatbyte-vnobis**
## Changes
Fix issue "Radio and checkbox filed values in the webhook end file export use the value field instead of the label which makes them unreadable"
See https://github.com/webiny/webiny-js/pull/2951 for previous code review comments

## How Has This Been Tested?
Manual

## Documentation
None

### CODE REVIEW

**Comment by adrians5j** [comment]
Thanks for opening a new PR @neatbyte-vnobis. Continuing the discussion here.

I like the screenshot, and I'd say it's the proper way forward.

Besides @SvenAlHamad confirming this is fine, I'd also have one last question (which @SvenAlHamad my also comment on):

image

Once we confirm, we'll soon be able to merge this.

Thank you @neatbyte-vnobis !

**Comment by SvenAlHamad** [comment]
Because this is a user facing information, I think it’s more readable if we don’t have the [] brackets.

**Comment by adrians5j** [comment]
I agree @SvenAlHamad.

Alright @neatbyte-vnobis, let's just apply this last change and we'll most probably be good to merge.

Thanks!

P.S. Let's apply the change for both non-label and label columns (so, both **Country Radio** and **Country Radio (Label)** columns).

**Review by adrians5j — APPROVED** [review]
Thanks @neatbyte-vnobis !

**Pull request merged**
