### PR TITLE
🙀 Simplify Security Plugins

### LINKED ISSUE #1034: Headless CMS Security Scopes
*Addressing the Security Scopes mentioned in #829 and #1018*

Here's how I envision headless security scopes:

##### Toggling Model security scopes
- we add a new section under **Security > Headless CMS** called **Models** *(see ss #1)*
- in this section, you select an existing environment *(see ss #2)*
- then, you select **read** / **preview** / **manage api** (imagine 3 different tabs) and you see a list with all resolvers associated to - that env & api type
- all resolvers above have 1 "Authorization Required" checkbox
- (checkboxes can be disabled and set to true/false for values we don't want to modify, ie: allow full AT access to read/preview api)

##### New user permissions
- we add a new accordion section in /users admin app route where we can set which headless cms resolvers the selected user can use (see ss #3)
- just as above, we will see a list with all resolvers
- the **environment** is selectable via a `<select>` input or sth similar

### Back End
- valid JWTs & PATs are automatically resolved into `context.user.id`, `context.user.access.scopes`, `context.user.access.fullAccess`... In the same fashion we can also resolve a new `context.user.access.headlessCmsScopes` field which contains our aforementioned cms permissions set via checkboxes
```js
eg:

context.user.access.headlessCmsScopes = {
    production: [
        "createBlogPost",
        "getBlogPost",
         ...
    ], 
    bassCannon: [
        "listBlogPosts",
         ...
    ],
    ...
}
```

### User stories solved *([see #1018](https://github.com/webiny/webiny-js/pull/1018#issuecomment-645175156))*
~~**us [1]** - already done~~
**us [1.1]** - we can add a disable / delete button in **/settings/cms/accessTokens?id=...**
**us [1.2]** - we can add a button that disables all **Security > Headless CMS > Models > /read API** checkboxes and sets them to false by default
~~**us [2]** - fixed in my PR #1018~~ (but i could rename the plugin from "context-cms-validate-access-token" to "context-cms-authorize" as it'll be more clear)
**us [3]** - whatever.
- we could give add an option under **Settings > Headless CMS** that allows users to set if the APIs are public by default, thus setting the earlier checkbox's default value (mentioned above at [1.2]). 
- we could also give them a note stating `Bro, your API is public by default. make sure you check your security scopes or you're gonna get your corporation's data crawled by russian hackers and exposed on liveleak.com when they create a new model`

**us [4]** - (actual **TODO**) will solve as explained above if we find it a good approach
**us [5]** - (actual **TODO**) will solve as explained above if we find it a good approach

### Questions / Remarks
**ps / question #1**: "The MANAGE API only needs JWT auth." actually, PATs should (and do currently) authenticate the user as well as the JWT does
**ps #2**: i didn't use hasScope (mentioned in #829) because i didn't need to

image
image
image

### PR DESCRIPTION
**Pull request by Fsalker**
## TODO
- [ ] update docs to reflect latest plugins changes
- [ ] polish Headless CMS Access Tokens form

## About
This PR introduces a couple of significant changes to the whole framework.

### 1. Changes in the `api-security` plugins
We simplified the security plugins, where the developer now only needs to register a single `type: security` plugin, which handles both authentication and authorization processes, via the `SecurityIdentity` class. This will certainly allow easier integration with other auth providers, like Auth0, Okta, you name it.

### 2. Headless CMS - Access Tokens use security scopes
Previously, if a user wanted to use read/preview API, they would need to create an access token, which would immediately grant full access. Now users can control what can be accessed via the access token, by assigning it needed security scopes.

### 3. Security scopes more flexible
Users can now use `*` when creating scopes. For example, `security:*` would give full permissions to `api-security` API. This also means just assigning the `*` scope gives the full-access to the API.

### 4. Simplified `context` plugins
To alter the `context` object, developers used the `type: context` plugins, which offered `preApply`, `apply`, and `postApply` methods. With this PR, we decided to reduce everything to a single `apply` method, which makes things clearer and also helps to prevent circular dependency situations.

### 5. A single context object
Until this PR, the `context` object sent to the Apollo GraphQL Server would be recreated, which may lead to confusion / inconsistencies. That's why the object created in the handler will now just be passed to the Apollo GraphQL Server, or in other words, a single `context` object will always be present.

### 6. Optimized PAT validation
In order to authenticate via PAT, we have to invoke the `validatePat` function, even when it was happening on the `api-security` handler itself, which can be done via a direct database call too. If we can avoid a function call, we should certainly do it, so we made the necessary changes.

### 7. Refactored tests
We had a couple of different variations on how we approached writing tests in a couple of `api-*` packages. We refactored the old variations and made them work with the latest approach we decided to go with (creating assertions against the complete handler, not just against the schema). The `api-headless-cms` package still contains some tests written in this "old" way, but at this point, it's OK, it's not critical. 

Another cool improvement in this department is that the auth is now working as in a real-world now. We no longer follow the approach `if (ENV === test) then ignore security`. You will need to pass JWTs in order to access and test protected resolvers.

### CODE REVIEW

**Comment by Fsalker** [comment]
**Main features so far**
-refactored authentication & authorization: now we have `type: authorization` and `type: authentication` plugins in order to support JWT, PAT (personal access token), AT auth (in the future, we will easily add Okta etc)
-added `slug` field to `CmsEnvironment` model
-updated `CmsEnvironment` test to include slugs
-ran prettier

**[WIP]**
-adding `listContentModels` field to `CmsEnvironment`
-updating `CmsEnvironment` test to include `listContentModels`

**Comment by Fsalker** [comment]
**New commits' summary**
-added `scopes` to `CmsAccessToken` (works well so far) + tests for these `scopes`
-[WIP] attempted to fix `listContentModels`. will get back to it later

**Comment by Fsalker** [comment]
**Latest commits**
-refactored `scopes` in `access tokens`' commodo/gql so that we can set scopes (as originally and logically intended...) 
-updated AT & env tests to include
-added `scopes` to front end
image
image
-added `slug` to cms envs in the FE. now they're fully functional
image
image

**Remaining WIP**
-fixing `context.models.CmsEnvironment` in `packages\api-headless-cms\src\content\plugins\authentication.ts` & sorting out `preApply` / `apply` plugins. we need it in order to generate cms scopes
-fixing `CmsContentModel` in `packages\api-headless-cms\src\plugins\models\environment.model.ts`. we need it to get `modelId` from each model belonging to an env (ps: oddly, CmsContentModel entries don't have an `environment` field, but the entries in mongodb do; i'll figure this out some other time)

**Comment by TommyJackson85** [comment]
Not sure if it's been done, but this file needs the correct CRUD scope passed into the scope array:
```packages/app-headless-cms/src/admin/plugins/welcomeScreenWidget.tsx```
Check ```line 22``` to find the array. Here it is:
```const plugin: AdminWelcomeScreenWidgetPlugin = {
    type: "admin-welcome-screen-widget",
    name: "admin-welcome-screen-widget-headless-cms",
    scopes: [],
    widget: {
```
It is to prevent  welcome widget from being viewed by unauthorised viewers.

For comparison purposes, see these similar examples:
Screenshot 2020-07-13 at 16 12 22

Screenshot 2020-07-13 at 16 12 36

Not sure if this PR is the right place for it but it did previously prevent me from finishing [Pull request 1078](https://github.com/webiny/webiny-js/pull/1078/files). Thanks anyway :)

**Comment by Pavel910** [comment]
@TommyJackson85 There are no scopes currently so an empty array is fine. We'll sort it out in the future, there's a lot going on with security at the moment.

**Comment by TommyJackson85** [comment]
> @TommyJackson85 There are no scopes currently so an empty array is fine. We'll sort it out in the future, there's a lot going on with security at the moment.

Ok, sure at a later stage so. If you want ill delete my suggestion and this comment. I don't want to complicate things.

**Comment by Pavel910** [comment]
@TommyJackson85 No need to delete anything :) Even better, you could open a separate issue for that particular problem so we can fix it when CMS scopes are ready 🚀

**Comment by Pavel910** [comment]
Closing this PR, it has morphed into something a lot bigger, coming in v5.

**Pull request closed without merging**
