### PR TITLE
fix: Made options plugins effective

### LINKED ISSUE #1177: Custom plugins are not reflected on the page builder
## This is:

- Bug

## Specifications

  - OS: Mac
  - Browser: Chrome

## Expected Behavior

When creating a new [page builder theme](http://docs.webiny.com/docs/webiny-apps/page-builder/development/themes/introduction), the changes are not effective; the default theme is active.

## Actual Behavior

When creating a new [page builder theme](http://docs.webiny.com/docs/webiny-apps/page-builder/development/themes/introduction), the changes should be effective.

## Steps to Reproduce the Problem

1. Follow this [example](http://docs.webiny.com/docs/webiny-apps/page-builder/development/themes/theme-configuration) to create a new page builder theme.
2. Change an h1 label name as below:
```
h1: {
       label: "Test heading 1",
       component: "h1",
       className: "webiny-pb-typography-h1"
 },
```
3. Check on the website to change a text in "Test heading 1"

## Possible Solution

Check on this file for the fix: `packages/app-template-admin-full/src/index.tsx`

### PR DESCRIPTION
**Pull request by TommyJackson85**
## Related Issue

Closes #1177

## Your solution

I just moved ```...(options.plugins || [])``` to the bottom of the array.
@Pavel910 Am I right, in that this works becuase the Array is itterated through accendently from the start to the end, with Options essentially overwriting previous data / value changes from the other plugins callbacks?

## How Has This Been Tested?

Will test this manually next.

## Screenshots (if relevant):
None yet.

### CODE REVIEW

**Comment by TommyJackson85** [comment]
I haven't gotten around to testing this yet. Will try tomorrow, if not Sunday. If you need this done asap and feel confident in it though by all means set this for review and merge it!

**Comment by Pavel910** [comment]
@TommyJackson85 yes, when this whole array is passed to `PluginsContainer` it will take care of only using the latest registered plugin, so user-provided plugins will override the once that are built into the app template.

**Comment by TommyJackson85** [comment]
@Pavel910 the setup for testing my changes (from the issue page) is taking me a bit of time to set up, and I'm a little time restrained with my current job. So if you feel happy with this change, feel free to merge it anyway! Otherwise I will come back to this later in the week.

**Comment by Pavel910** [comment]
@TommyJackson85 thanks for reminding me, totally forgot about this as we are all over the place with the new stuff. Merging this, it's perfectly fine! 🚀 Thanks!

**Pull request merged**
