### PR TITLE
feat: switch page builder to use new blocks

### PR DESCRIPTION
**Pull request by neatbyte-vnobis**
## Changes
Change Page Builder page to use new Page Blocks and old Page Elements at same time

## How Has This Been Tested?
Manual testing

## Documentation
None

### CODE REVIEW

**Review by Pavel910 — APPROVED** [review]
This looks good @neatbyte-vnobis 👍

**Comment by brunozoric** [comment]
Just a note that this PR will require an update to user project - remove old plugins.

**Comment by SvenAlHamad** [comment]
Can we keep this in a separate branch until we fully complete the project? We could do a back merge after we close every PR, just so the branch is up to date.

**Comment by Pavel910** [comment]
Yes, there's an umbrella PR. This is not going into next yet.

**Pull request merged**
