### PR TITLE
fix: fix building graphql types for nested dynamic zones

### PR DESCRIPTION
**Pull request by ghost**
Changed the way the type is created within the dynamic zone field to include nested dynamic zones.

### CODE REVIEW

**Comment by brunozoric** [comment]
hi @alexvanloon-dh 
Unfortunately it is not only the GraphQL types on the UI side but some stuff in the API.
We need to sort that first and then we will evaluate your PR.

thanks :)

**Comment by brunozoric** [comment]
Hi @alexvanloon-dh 

At the moment we cannot support Dynamic Zone in the Object field. We have some architectural changes to implement before we can make this possible.

There is a [PR](https://github.com/webiny/webiny-js/pull/3160) which will disable adding Dynamic Zone in the Object field.

**Comment by ghost** [comment]
Hi @brunozoric 

Thanks for replying, do you have any idea if/when this will be possible? That will help us to decide to wait or find a workaround.

**Comment by brunozoric** [comment]
Hi @alexvanloon-dh 

best case scenario: end of next querter (start of July)
worst case: not sure exactly as we need to do a lot architectural changes regarding CMS Models to make this work properly

**Comment by ghost** [comment]
Ok thanks

**Comment by brunozoric** [comment]
Dynamic Zone will work in Object field in 5.38.0. Closing...

**Pull request closed without merging**
