### PR TITLE
fix(ci-plugin-scaffold-ci): add files for GitHub Actions workflows

### LINKED ISSUE #2554: Problem creating workflows on executing CD/CI scaffold
### Version

5.29.0

### Operating System

Mac OS

### Browser

_No response_

### What are the steps to reproduce this bug?

From the project folder, execute `yarn webiny scaffold` and select Setup CD/CI into an existing repo.

### What is the expected behavior?

Github workflows created successfully.

### What do you see instead?

I got this only error (all other steps worked):

Creation of GitHub Actions workflows failed with the following message: ENOENT: no such file or directory, scandir '[...]/node_modules/@webiny/cli-plugin-scaffold-ci/githubActions/files/workflows'

Here is the Stacktrace:

```
✘ Creation of GitHub Actions workflows failed with the following message: ENOENT: no such file or directory, scandir '[...]\node_modules\@webiny\cli-plugin-scaffold-ci\githubActions\files\workflows'
✔ Long-lived dev, staging, and prod branches created.
✘ Enabling protection for long-lived branches failed with the following message: Upgrade to GitHub Pro or make this repository public to enable this feature.
✔ Set dev as the default branch.
✘ Creation of pr, dev, staging, and prod code repository environments failed with the following message: Not Found

✔ CI/CD partially set up (total errors: 3).
```

### Additional information

_No response_

### Possible solution

_No response_

### PR DESCRIPTION
**Pull request by ryohei-kamiya**
## Changes
Close #2554 

## How Has This Been Tested?
Manually. 
I checked that files for GitHub Actions workflows exists after the build.

スクリーンショット 2022-09-01 2 22 05

### CODE REVIEW

**Comment by adrians5j** [comment]
Hey @ryohei-kamiya, thanks for the submission. Actually, while we're at it, I'm [trying to see](https://github.com/webiny/webiny-js/pull/2601) if just adding `dot: true` internally will also work.

So, we would not add it as an arg, but we'd do it all the time. But I do appreciate the thought of "let's not put it directly so that we don't break anything" mindset. :)

In any case, I'll let you know if this works. If so, if you want, you can do the same change in your PR, and I'll close mine. This way your contribution and the time you invested will get noted.

**Comment by adrians5j** [comment]
Hey @ryohei-kamiya, it seems mine https://github.com/webiny/webiny-js/pull/2601 PR is all green in CI/CD, so it can be merged. But then again, I just wanted to double check with you if you'd like to make the same change and we merge your PR first? 

Let me know when you can. The alternative is we merge the linked PR and we just close this one.

Thanks again!

**Comment by ryohei-kamiya** [comment]
Hi @adrians5j , thank you for your review!
I wasn't sure if it was correct to always specify the `dot` option due to the following two concerns.

1. Does it affect other existing packages?
2. Is there any risk that files that you do not want to include (for example, .env at local) will be included in the build process and packaging process in the future?

Therefore, I chose to do what I thought was safer.
( But I think I may have been overly cautious. In addition, I think the name of the argument is not cool :) )

Without those risks, I think your simpler code would be better, so feel free to close this PR.
If this interesting product improves as a result, I don't mind my commits being not noted.

Thank you!

**Comment by adrians5j** [comment]
Agreed with everything you said! 

I merged the linked PR, so we're a bit faster.

Thanks a lot for your time @ryohei-kamiya! 

Cheers 🍻

**Pull request closed without merging**
