### PR TITLE
fix: fix border not getting applied to an image

### PR DESCRIPTION
**Pull request by neatbyte-vnobis**
## Changes
Fix regression issue "Border not getting applied to an image"

## How Has This Been Tested?
Manual

## Documentation
None

### CODE REVIEW

**Comment by SvenAlHamad** [comment]
Tested this one. Looks good. Thanks for sorting it out!
@Pavel910 - This has scss file changes inside user's project, pleases see if any additional migration scripts might be needed for our next release.

**Comment by Pavel910** [comment]
@SvenAlHamad ok, I'll squeeze this in today.

**Comment by Pavel910** [comment]
@neatbyte-vnobis I'll resolve the conflicts myself and merge this a bit later. Thanks!

**Comment by Pavel910** [comment]
I've extracted the necessary changes into the upgrade script for 5.34.0, and the rest is not needed any longer in our repo. I've informed @adrians5j to integrate these changes into the new rendering engine. With that, I'm closing this PR. Thanks @neatbyte-vnobis and @SvenAlHamad!

**Pull request closed without merging**
