### PR TITLE
fix: 🐛  fix the wrong packages version

### PR DESCRIPTION
**Pull request by boyuan459**
fix the wrong packages version for headless-latest branch

BREAKING CHANGE:
none

### CODE REVIEW

**Comment by Pavel910** [comment]
@boyuan459 thanks, we've fixed this literally a few minutes ago 👍 Thanks anyway :) 🎉

**Comment by boyuan459** [comment]
@Pavel910 could you kindly check again, I still get the error, thanks.
error Couldn't find package "@webiny/handler@^1.0.0" required by "@webiny/api-security@3.1.0" on the "npm" registry

**Comment by Pavel910** [comment]
@boyuan459 right, there one more, in the `devDependencies`. I'll merge your PR to add that one in 🚀

**Comment by Pavel910** [comment]
@boyuan459 done! Let me know if there is more :) Cheers!

**Pull request merged**
