### PR TITLE
feat: add page category to page template settings

### PR DESCRIPTION
**Pull request by neatbyte-vnobis**
## Changes
Implements issue "Add page category to page template settings".

FYI: Page Category can be selected only for Page Templates (see Settings inside Template Editor) for now.
For Pages WIP (will be a select in Settings inside Page Editor).

## How Has This Been Tested?
Manual

## Documentation
None

### CODE REVIEW

**Comment by SvenAlHamad** [comment]
I've tested this and I'm good with how it looks from my end.

**Review by adrians5j — APPROVED** [review]
Thanks @neatbyte-vnobis, looks good, merging this!

P.S. While I have the opportunity, just wanted to highlight the below ⬇️ 

image

I'm sure you're all aware of this, but yeah, sooner or later we'll need undo the hardcode here and enable users to select the layout and page category upon creating a new page template.

**Comment by neatbyte-vnobis** [comment]
@adrians5j @SvenAlHamad 
I still in progress with Page Category select (on Page Editor Settings)
Or it is not required?

**Comment by adrians5j** [comment]
Not sure what you meant here, but I will be merging this PR as soon as CI is 🟢 .

**Comment by neatbyte-vnobis** [comment]
@adrians5j 
image
It is not mandatory to be part of this PR, but I was planning to add it in its scope.
FYI Page Settings is a "class" component (not functional)

**Comment by Pavel910** [comment]
@neatbyte-vnobis let's hold on with that Page Settings update, as that is a horrible black hole, I don't want you to waste time on it. I'd rather review that task myself, and just so you know, that class is the last remaining example of a failed experiment from the past. We're soon to refactor it using a far better experiment 😅 so let's not do anything here if it's not mandatory.

**Comment by adrians5j** [comment]
I'm also for not expanding the scope and tackling this in a separate PR.

CI is 🟢 , merging this.

**Comment by Pavel910** [comment]
@neatbyte-vnobis can you please point me to a task in notion or where you had this defined, so I can have a look at the requirements? Thanks!

**Comment by neatbyte-vnobis** [comment]
@Pavel910 
Please try this link - https://webiny.notion.site/Page-Builder-Bug-Fixes-Improvements-0036c7406813427694a8bda88d754e7b?p=ff15497679d64b9eb557dedcee6d7394&pm=s

**Comment by Pavel910** [comment]
@neatbyte-vnobis works, thank you!

**Comment by Pavel910** [comment]
@neatbyte-vnobis ok I see, there should be a Category selector in here:

CleanShot 2023-03-13 at 10 50 14

As I said, leave it like that for now, I'll add this myself before the next release. I really don't want you to sort through that core, and battle those concepts, since it's literally the only view in the system left to use that way of building UI, so it's not like you'll learn anything from it.

**Pull request merged**
