### PR TITLE
fix: removed searchModel from headless cms model fields text.ts file

### LINKED ISSUE #1097: Headless CMS - remove old `searchModel` property
This field isn't used anymore so we should remove it. It's present on all fields in `packages/api-headless-cms/src/content/plugins/modelFields/`

image

### PR DESCRIPTION
**Pull request by TommyJackson85**
## Related Issue

Closes #1097

## Your solution
THIS IS CURRENTLY A DRAFT AND NOT READY FOR MERGING

removed searchModel from text.js.
@doitadrian am I to remove ```searchModel``` from all files under modelFields files as I have done so far for text.ts?
I will keep updating this initial posting and heading until I understand more.

## How Has This Been Tested?
Running yarn start on apps/admin.
Will see results from creating pull request.
@doitadrian Any other I can test this? The issue you posted didn't have a lot of details.

## Screenshots (if relevant):
None yet.

### CODE REVIEW

**Comment by Ashu96** [comment]
@TommyJackson85 good work :+1: 

Yeah. We simply want to remove `searchModel` from all `modelFields`. The same thing you have done with `packages/api-headless-cms/src/content/plugins/modelFields/text.ts `

**Comment by TommyJackson85** [comment]
> @TommyJackson85 good work 👍
> 
> Yeah. We simply want to remove `searchModel` from all `modelFields`. The same thing you have done with `packages/api-headless-cms/src/content/plugins/modelFields/text.ts `

Ok I will continue this so. Thanks for the feedback!

**Comment by TommyJackson85** [comment]
I removed the searchModel references, including the one from the types file. Was there any I was supposed to keep? Check the file changes for me.

I also pulled from the main master branch again to keep my repository updated as there was some significant changes done recently.

**Comment by TommyJackson85** [comment]
I removed interface Module from namespace NodeJS to fix a bug thats giving a commodo error. Made the same changes to  [PR #1111](https://github.com/webiny/webiny-js/pull/1111) and it seemed to work. (my previous commit message needs to be corrected as I didnt remove namespace NodeJS all together.):
Screenshot 2020-07-11 at 20 26 31

Its passing now but, I am getting an error related to my commit messages still, is there anyway I can update them to fix the error?

**Pull request merged**
