### PR TITLE
fix: change order of block categories

### PR DESCRIPTION
**Pull request by neatbyte-vnobis**
## Changes
Fix issue "Order of block categories"

## How Has This Been Tested?
Manual

## Documentation
None

### CODE REVIEW

**Review by adrians5j — COMMENTED** [review]
Cool. BTW, what about the page editor? 

Do we need to do any changes there?

**Comment by neatbyte-vnobis** [comment]
@adrians5j 
It is already sorted properly on Page Editor.
So no need for any changes there.

**Comment by adrians5j** [comment]
Thanks @neatbyte-vnobis. 

The code looks good @SvenAlHamad. When you get the chance, let me know if we can merge this.

**Comment by neatbyte-vnobis** [comment]
@adrians5j 
Sorry, there is indeed an issue there (it is sorted by blocks)
I will fix it shortly

**Comment by adrians5j** [comment]
Sounds good @neatbyte-vnobis 👍🏻

**Comment by neatbyte-vnobis** [comment]
@adrians5j fixed now

**Comment by adrians5j** [comment]
Thanks @neatbyte-vnobis.

The code looks good @SvenAlHamad. When you get the chance, let me know if we can merge this.

**Comment by SvenAlHamad** [comment]
Let's merge this one

**Pull request merged**
