### PR TITLE
chore: typing error in prettified version

### PR DESCRIPTION
**Pull request by SyedUmerHasan**
This is added in order to make easier and understandable typescript issue to fix raw error into prettified error

## Changes

Closes #ISSUE_NUMBER

### CODE REVIEW

**Comment by SyedUmerHasan** [comment]
@doitadrian  please look into this, if it looks good

**Comment by adrians5j** [comment]
Thanks for taking the time to check this out.

I only have one question - do we really need this? I'm asking because it seems this is already enabled by default:
https://www.typescriptlang.org/tsconfig#pretty

**Comment by Pavel910** [comment]
@SyedUmerHasan please post screenshots with PRs which affect visual parts of UI/terminal.  As @doitadrian mentioned, pretty output is on by default. If you have different information, please post before/after screenshots for us to see.

Also, please note that in our contributing guide, we require every community PR to have an issue, which we then triage, and provide our feedback and possibly instructions about implementation. It's easier to create an issue and verify the problem/feature, then spending time on a PR which may get rejected.

**Comment by adrians5j** [comment]
Closing this. Feel free to re-open if you feel like it.

**Pull request closed without merging**
