### PR TITLE
Feat: Menu element plugin package for page builder

### LINKED ISSUE #1176: Menu element plugin for Page Builder
## This is:
- Feature request

## Detailed Description
We want to create a new element plugin for Page Builder, which will allow us to use Menus, defined in the Menus module, as part of the page content. 

image

Once the user creates a new menu, he should be able to go to the page editor, and add a menu element, select which menu he wants to render, and select a component to render the menu.

To implement this, create a new package in the repository called `app-plugin-page-builder-menu-element`. Test your package by adding the plugin to the `admin` app. Also, add the render plugins to the `site` app and test rendering on the site.

## References
The following references contain everything you need to implement this feature. To try out similar plugins, try adding a Form or a Pages List element to your page.

*MUST READ*: A tutorial on creating Page Builder element plugins:
https://docs.webiny.com/docs/guides/creating-iframe-element-plugin

A very similar plugin for Mailchimp: 
https://github.com/webiny/webiny-js/tree/master/packages/app-mailchimp

An existing implementation of a very similar plugin to embed forms into the page editor:
https://github.com/webiny/webiny-js/tree/master/packages/app-form-builder/src/page-builder

An example of `PagesList` element and how it loads different renderers via plugins:
https://github.com/webiny/webiny-js/blob/master/packages/app-page-builder/src/render/plugins/elements/pagesList/index.tsx

A reference to `PagesList` element plugin for the editor:
https://github.com/webiny/webiny-js/tree/master/packages/app-page-builder/src/editor/plugins/elements/pagesList

### PR DESCRIPTION
**Pull request by TommyJackson85**
## Related Issue

Closes #1176

## Your solution

Creating a menu plugin package used for the app page builder package.

Creating element plugin within the app page builder.

## How Has This Been Tested?
In progess.

## Screenshots (if relevant):
None yet.

### CODE REVIEW

**Comment by TommyJackson85** [comment]
I'll pick this up on Thursday again guys. 🙌🏻

**Comment by TommyJackson85** [comment]
@Pavel910 Does the render folder in PagesList receive the page list data for the modal popup (used to find page list data) ?

**Comment by Pavel910** [comment]
@TommyJackson85 when rendering, each `element` passes its data to the appropriate plugin, in this case `PagesList`, so you receive that data at this reference: `packages/app-page-builder/src/render/plugins/elements/pagesList/index.tsx:13`. `element` will be the whole element object from the editor.

**Comment by TommyJackson85** [comment]
> @TommyJackson85 when rendering, each `element` is passed to the appropriate plugin, in this case `PagesList`, so you receive that data at this reference: `packages/app-page-builder/src/render/plugins/elements/pagesList/index.tsx:13`. `element` will be the whole element object from the editor.

@Pavel910 and when 

   const components = getPlugins<PbPageElementPagesListComponentPlugin>(
        "pb-page-element-pages-list-component"
    );

Is called from the Editor folder's PagesList.tsx file, does it call the Render folders plugin you are referring to ?

**Comment by Pavel910** [comment]
@TommyJackson85 same thing is happening. Editor and Render plugins work the same way, they always receive an `element` and it's up to the plugin to handle the rendering.

**Comment by Pavel910** [comment]
This is the `editor` plugin, see how the `render` function is identical to the one in `render` folder: `packages/app-page-builder/src/editor/plugins/elements/pagesList/index.tsx:65`.

**Comment by TommyJackson85** [comment]
Ok so the editor plugin has no interaction with the render plugin?

I'm just wondering how the editor plugin call (the one I copied in my previous comment) is receiving data. I assume it's using a graphql query but I'd like to know where this query request is being called.
Is the graphql call located within editor do PagesList or else where ? It doesn't pass in the query till later in the file.

**Comment by Pavel910** [comment]
@TommyJackson85 Look I'm really sorry, but I can't point you to every single line within the same folder. Just navigate the imports, read the code and you'll find everything. The concept of PB plugins is described in this article:

https://docs.webiny.com/docs/guides/creating-iframe-element-plugin/

Same rules apply to all other plugins. The editor only passes the `element` data to your plugin (which I linked in my previous comment), and the rest is all handled by your plugin - so you only need to read the code in the plugin folder (`pagesList` for example). There's no magic there. 

Editor plugins are completely isolated from `render` plugins. If they do share a React component, you'll find it by reading the imports.

Please go over that guide I linked above to learn how stuff is connected in details.

**Comment by TommyJackson85** [comment]
Now the Menu adder is currently working like an application used to display a list of menu data, very simular to the PagesLists editor tool.
This isn't what we wan't obviously but its only cause I was using PagesLists as a rough template. I will look through the other examples now from the initial issue report.

**Pull request closed without merging**
