### PR TITLE
fix: change revisions order to latest on top

### PR DESCRIPTION
**Pull request by neatbyte-vnobis**
## Changes
Resolve issue "List revisions - latest on top".

## How Has This Been Tested?
Manual

## Documentation
None

### CODE REVIEW

**Comment by neatbyte-vnobis** [comment]
@Pavel910 @adrians5j @SvenAlHamad 
While working on this feature I've seen that Revision Selector behaves unexpectedly, when we select one of the revisions (v7 for example) and reopen Revision Selector menu, instead of highlighting selected revision (v7) it will highlight the first revision in the list.

So I want to know what should we do about it, should we leave it as it is right now (highlight first revision in the list) or should we change it to highlight revision that has been selected?

image

**Comment by adrians5j** [comment]
Let's rather do this sorting on the backend.

Just because the backend already has this functionality built, it's just a matter of exposing it via GQL field params.

This is the CRUD method:
https://github.com/webiny/webiny-js/blob/next/packages/api-page-builder/src/graphql/crud/pages.crud.ts#L1252

Storage operations, both DDB and DDB+ES, support the `sort` param, e.g.:

packages/api-page-builder-so-ddb/src/operations/pages/index.ts:771

**Review by adrians5j — CHANGES_REQUESTED** [review]
Let's rather do this sorting on the backend.

Just because the backend already has this functionality built, it's just a matter of exposing it via GQL field params.

This is the CRUD method:
https://github.com/webiny/webiny-js/blob/next/packages/api-page-builder/src/graphql/crud/pages.crud.ts#L1252

Storage operations, both DDB and DDB+ES, support the `sort` param, e.g.:

packages/api-page-builder-so-ddb/src/operations/pages/index.ts:771

**Review by adrians5j — APPROVED** [review]

**Review by adrians5j — CHANGES_REQUESTED** [review]
Let's check failing tests before merge.

**Pull request merged**
