### PR TITLE
feat: add copy form submission options

### PR DESCRIPTION
**Pull request by neatbyte-vnobis**
## Changes
Fix issue "Add copy submission option to details modal"

## How Has This Been Tested?
Manual

## Documentation
None

### CODE REVIEW

**Review by adrians5j — CHANGES_REQUESTED** [review]
Cool feature and UX.

Two improvements here.

1. Can we add a snackbar once a user clicks on the buttons?
So, once button is clicked, we say "CSV data copied to clipboard." / "JSON data copied to clipboard."

2. Can we have the min-width for the dialog? Just accidentally saw this:
image

Thanks!

**Comment by SvenAlHamad** [comment]
@neatbyte-vnobis - I've got two comments on this one:

1. When copying json, can it be prettified, so it looks nicer if I need to share it on slack or similar. 

2. When I click on any of the form submissions, and the modal opens with the details, the "Copy as JSON" button is focused, and I'm not sure why.

**Comment by adrians5j** [comment]
Hey @neatbyte-vnobis , this looks good. Please just check CI, mainly "Static code analysis" check: https://github.com/webiny/webiny-js/actions/runs/4172922163/jobs/7224736270

Thanks!

**Review by adrians5j — APPROVED** [review]
Thank you @neatbyte-vnobis !

**Pull request merged**
