### PR TITLE
fix: fix breaking page rendering if main menu absent

### LINKED ISSUE #2579: Default Page Builder theme breaks page rendering if main menu is not present
### Version

5.30

### Operating System

MacOs

### Browser

Safari

### What are the steps to reproduce this bug?

Delete the main-menu from the page builder and try to preview a page. You get a blank page with errors in the console.

### What is the expected behavior?

Page to be rendered correctly.

### What do you see instead?

Blank screen 

### Additional information

The default theme expects that there is a menu with main-menu slug present. If such a menu doesn’t exist, it breaks the page rendering.

### Possible solution

Inside the theme we need to add a check if a menu exists, and a check to see if the menu has any items.

### PR DESCRIPTION
**Pull request by neatbyte-vnobis**
## Changes
Fix issue "Default Page Builder theme breaks page rendering if main menu is not present"
Closes #2579

## How Has This Been Tested?
Manual

## Documentation
None

### CODE REVIEW

**Review by Pavel910 — CHANGES_REQUESTED** [review]
@neatbyte-vnobis please also update this file in the actual template package:
`packages/cwp-template-aws/template/common/apps/theme/pageBuilder/components/Menu.tsx`

In general, whatever changes you do within the `apps/` folder, you also need to propagate those changes to the `cwp-template-aws` package, because that's the source of truth for new projects, created from NPM.

**Comment by neatbyte-vnobis** [comment]
@Pavel910 I have updated `cwp-template-aws`

**Comment by SvenAlHamad** [comment]
The fix seems to be working fine. @Pavel910 if the code side looks good, we can merge it.

**Review by adrians5j — APPROVED** [review]
Good to merge. 🙏🏻

**Pull request merged**
